# parameters.py

TICKER = 'XOM'  # Example small to medium-cap biotech company
START_DATE = '2023-01-01'
END_DATE = '2024-01-01'
MEAN_REVERSION_PERIOD = 10
MEAN_REVERSION_DEV_FACTOR = 2
CRSI_RSI_PERIOD = 5
CRSI_STREAK_RSI_PERIOD = 3
CRSI_RANK_PERIOD = 100
TREND_FOLLOWING_PERIOD = 100
BREAKOUT_PERIOD = 20
STOP_LOSS = 0.02
TAKE_PROFIT = 0.04
CRSI_LOWER_THRESHOLD = 30
CRSI_UPPER_THRESHOLD =80
VWAP_CONDITION = False